--------------------------------------------------------------------------------
--Setup
--------------------------------------------------------------------------------
CREATE TABLE COMPANY(EMPLOYEE_ID NUMBER NOT NULL,EMPLOYEE_NAME VARCHAR2(10),MANAGER_ID NUMBER,SALARY NUMBER);

INSERT INTO COMPANY VALUES(1,'FRED',NULL,100000);
INSERT INTO COMPANY VALUES(2,'BARNEY',1,50000);
INSERT INTO COMPANY VALUES(3,'WILMA',1,50000);
INSERT INTO COMPANY VALUES(4,'BETTY',3,40000);
INSERT INTO COMPANY VALUES(5,'PEBBLES',3,40000);
INSERT INTO COMPANY VALUES(6,'BAM-BAM',4,20000);
INSERT INTO COMPANY VALUES(7,'DINO',4,20000);
INSERT INTO COMPANY VALUES(8,'HOPPY',4,40000);